// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ClickNDone.Core;

namespace ClickNDone.iOS
{
	public partial class SugerenciasController : MyViewController
	{
		readonly UserModel UserModel = (UserModel)DependencyInjectionWrapper.Instance.ServiceContainer ().GetService (typeof(UserModel));


		public SugerenciasController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.LoadLeftbarButton ();
			this.AddKeyboarListeners ();
			var user = UserModel.User;
			txtUserName.Text = user.names;
			txtApellido.Text = user.surnames;

			btnSendComment.TouchUpInside += (sender, e) => 
			{
				new UIAlertView("Envío Exitioso", "Su sugerencia fue enviada con exito", null, "Ok").Show();
				this.txtComments.Text = "";
			};

			btnClean.TouchUpInside += (sender, e) => 
			{
				this.txtComments.Text = "";
			};
		}
	}
}
